import {useCallback,useEffect,useRef,useState} from 'react';
import {View,Text,TextInput,Pressable,ScrollView,StyleSheet,Alert,Linking,AppState,ActivityIndicator,Platform} from 'react-native';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import Mapbox from '@rnmapbox/maps';
import * as Location from 'expo-location';
import * as Network from 'expo-network';
import * as Crypto from 'expo-crypto';
import {outcomes,outcomeLabels,outcomeColors,latestVisit,shiftState,fieldMinutes,validateLead,dayKey,minutesOnDay,type Outcome,type Property,type Position,type ShiftAction,type QueueEntry} from '@canvass/core';
import {configured,supabase,loadState,refresh,latestEvents,command,submit,sync,outbox,updateState,clearLocal,repairProjection,type LocalState} from './runtime';
import {reconcileTracking,stopTracking,startTracking} from './tracking';
const mapToken=process.env.EXPO_PUBLIC_MAPBOX_TOKEN;if(mapToken)Mapbox.setAccessToken(mapToken);
const fmt=(minutes:number)=>`${Math.floor(minutes/60)}h ${Math.floor(minutes%60)}m`;
function Button({title,onPress,secondary=false,disabled=false}:{title:string;onPress:()=>void;secondary?:boolean;disabled?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button,secondary?s.secondary:null,disabled?{opacity:.5}:null]}><Text style={[s.buttonText,secondary?{color:'#b83e29'}:null]}>{title}</Text></Pressable>;}
export default function App(){return <SafeAreaProvider><FieldApp/></SafeAreaProvider>;}
function FieldApp(){
 const [state,setState]=useState<LocalState|null>(null),[entries,setEntries]=useState<QueueEntry[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[screen,setScreen]=useState<'map'|'doors'|'time'|'sync'>('map'),[selected,setSelected]=useState<Property|null>(null),[offline,setOffline]=useState(false),[newPassword,setNewPassword]=useState(false);
 const viewRefresh=useCallback(async()=>{setState(await loadState());setEntries(await outbox.entries());},[]);
 const connect=useCallback(async()=>{let failure='';try{await sync();}catch(e){failure=e instanceof Error?e.message:'Work saved on your phone.';}try{await refresh();}catch(e){failure=e instanceof Error?e.message:failure;}const current=await loadState();if(current.user&&!current.user.active)await stopTracking();setMessage(failure);await viewRefresh();},[viewRefresh]);
 useEffect(()=>{let alive=true;void(async()=>{await repairProjection();if(alive)await viewRefresh();if(configured){try{await refresh();await reconcileTracking();}catch{}if(alive)await viewRefresh();}})();const timer=setInterval(()=>{void Network.getNetworkStateAsync().then(n=>{setOffline(n.isInternetReachable===false);if(n.isInternetReachable!==false)void connect();else void viewRefresh();});},30000);const app=AppState.addEventListener('change',status=>{if(status==='active'){supabase?.auth.startAutoRefresh();void(async()=>{await connect();await reconcileTracking();await viewRefresh();})();}else supabase?.auth.stopAutoRefresh();});return()=>{alive=false;clearInterval(timer);app.remove();};},[connect,viewRefresh]);
 useEffect(()=>{async function handle(url:string){const hash=url.split('#')[1]??url.split('?')[1]??'';const params=new URLSearchParams(hash);const access_token=params.get('access_token'),refresh_token=params.get('refresh_token');if(access_token&&refresh_token){await supabase?.auth.setSession({access_token,refresh_token});setNewPassword(true);}}void Linking.getInitialURL().then(url=>{if(url)void handle(url);});const subscription=Linking.addEventListener('url',e=>void handle(e.url));return()=>subscription.remove();},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);try{await fn();}catch(e){setMessage(e instanceof Error?e.message:'Please try again.');}finally{await viewRefresh();setBusy(false);}}
 if(!state)return <SafeAreaView style={s.root}><ActivityIndicator color="#174c3c"/></SafeAreaView>;
 if(!configured)return <SafeAreaView style={s.root}><View style={s.login}><Text style={s.wordmark}>WE ROOF</Text><Text style={s.h1}>Ready for your field team.</Text><Text style={s.body}>Connect the company’s Supabase and Mapbox credentials, then install a development build to start your pilot.</Text><Text style={s.note}>Setup instructions are included in docs/SETUP.md in the project.</Text></View></SafeAreaView>;
 if(newPassword)return <PasswordSetup onDone={()=>{setNewPassword(false);void connect();}}/>;
 if(!state.user)return <Login busy={busy} message={message} onLogin={(email,password)=>void run(async()=>{const {error}=await supabase!.auth.signInWithPassword({email,password});if(error)throw error;await refresh();})}/>;
 const events=latestEvents(state),status=shiftState(events),active=status==='active'&&state.user.active;
 async function shift(action:ShiftAction){const id=action==='clock_in'?Crypto.randomUUID():events[0]?.shift_id;if(!id)return;await submit(command('shift',{action,shift_id:id}));if(action==='clock_in'||action==='break_end')await startTracking();else await stopTracking();try{await sync();}catch{};}
 async function addDoor(lon?:number,lat?:number){if(!active){setMessage('Clock in or end your break to record a door.');return;}if(lon===undefined||lat===undefined){const permission=await Location.getForegroundPermissionsAsync();if(permission.granted){const p=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});lon=p.coords.longitude;lat=p.coords.latitude;}else {const center=state!.data.territories[0]?.boundary.coordinates[0][0];if(!center)throw Error('Choose a house on the map or enable location.');[lon,lat]=center;}}
 let address='';try{const {data}=await supabase!.functions.invoke('geocode',{body:{longitude:lon,latitude:lat}});address=data?.address??'';}catch{}
 const existing=state!.data.properties.find(p=>Math.abs(p.longitude-lon!)<.00003&&Math.abs(p.latitude-lat!)<.00003);
 setSelected(existing??{id:Crypto.randomUUID(),company_id:state!.user!.company_id,created_by:state!.user!.user_id,territory_id:null,address,latitude:lat!,longitude:lon!,do_not_knock:false,version:1});}
 async function download(){if(!mapToken)throw Error('Mapbox is not configured.');for(const t of state!.data.territories.filter(t=>!t.archived)){const ring=t.boundary.coordinates[0],lons=ring.map(p=>p[0]),lats=ring.map(p=>p[1]);const name=`territory-${t.id}`;const pack=await Mapbox.offlineManager.getPack(name);if(pack)await Mapbox.offlineManager.deletePack(name);
 await new Promise<void>((resolve,reject)=>{void Mapbox.offlineManager.createPack({name,styleURL:Mapbox.StyleURL.Street,minZoom:10,maxZoom:18,bounds:[[Math.max(...lons),Math.max(...lats)],[Math.min(...lons),Math.min(...lats)]]},(_region,progress)=>{if(progress.percentage>=100)resolve();},(_region,error)=>reject(Error(String(error)))).catch(reject);});await updateState(st=>({...st,downloaded_territory_ids:[...new Set([...st.downloaded_territory_ids,t.id])]}));}setMessage('Assigned maps downloaded. Door history is saved on this phone.');}
 if(selected)return <DoorForm state={state} property={selected} busy={busy} cancel={()=>setSelected(null)} save={(payload)=>void run(async()=>{await submit(command('visit',{...payload,shift_id:events[0].shift_id}));setSelected(null);setMessage('Door recorded.');try{await sync();}catch{};})}/>;
 return <SafeAreaView style={s.root}><View style={s.header}><View><Text style={s.wordmark}>WE ROOF</Text><Text style={s.small}>{state.user.name}</Text></View><Pressable accessibilityRole="button" onPress={()=>setScreen('sync')} style={s.statusPill}><Text style={s.statusText}>{offline?'Offline':entries.length?`${entries.length} pending`:'Saved'}</Text></Pressable></View><View style={s.shiftBar}><View><Text style={s.sectionLabel}>{active?'IN THE FIELD':status==='break'?'ON BREAK':'OFF SHIFT'}</Text><Text style={s.shiftTime}>{fmt(fieldMinutes(events))}</Text></View><View style={s.shiftButtons}>{!state.user.active?<Text style={s.warningText}>Account deactivated</Text>:status==='active'||status==='break'?<><Button title={active?'Take break':'End break'} disabled={busy} secondary onPress={()=>void run(()=>shift(active?'break_start':'break_end'))}/><Button title="Clock out" disabled={busy} onPress={()=>Alert.alert('End your shift?','Field time and location tracking will stop.',[{text:'Keep working',style:'cancel'},{text:'Clock out',onPress:()=>void run(()=>shift('clock_out'))}])}/></>:<Button title="Clock in" disabled={busy} onPress={()=>void run(()=>shift('clock_in'))}/>}</View></View>
 {state.tracking_error&&active?<Pressable onPress={()=>void Linking.openSettings()} style={s.warning}><Text style={s.warningText}>{state.tracking_error} Tap to open Settings.</Text></Pressable>:null}{message?<Pressable onPress={()=>setMessage('')} style={s.message}><Text style={s.note}>{message}</Text></Pressable>:null}
 {screen==='map'?<View style={s.mapContent}><View style={s.mapHeading}><Text style={s.h2}>Your assigned territory</Text><Text style={s.note}>Tap a house to record a door.</Text></View>{mapToken?<Mapbox.MapView style={{flex:1}} styleURL={Mapbox.StyleURL.Street} onPress={e=>{if(e.geometry.type==='Point')void run(()=>addDoor(e.geometry.coordinates[0],e.geometry.coordinates[1]));}}><Mapbox.Camera zoomLevel={14} centerCoordinate={state.data.territories[0]?.boundary.coordinates[0][0]??[-78.166,39.174]}/>{active?<Mapbox.LocationPuck/>:null}<Mapbox.ShapeSource id="territories" shape={{type:'FeatureCollection',features:state.data.territories.filter(t=>!t.archived).map(t=>({type:'Feature',properties:{color:t.color},geometry:t.boundary}))}}><Mapbox.FillLayer id="areas" style={{fillColor:['get','color'],fillOpacity:.1}}/><Mapbox.LineLayer id="boundaries" style={{lineColor:['get','color'],lineWidth:2,lineDasharray:[3,2]}}/></Mapbox.ShapeSource><Mapbox.ShapeSource id="doors" shape={{type:'FeatureCollection',features:state.data.properties.map(p=>{const v=latestVisit(state.data.visits,p.id),o=p.do_not_knock?'do_not_knock':v?.outcome;return {type:'Feature',id:p.id,properties:{id:p.id,color:o?outcomeColors[o]:'#64748b',label:o?outcomeLabels[o]:'No visits',symbol:o==='do_not_knock'?'×':o==='inspection_requested'?'✓':''},geometry:{type:'Point',coordinates:[p.longitude,p.latitude]}};})}} onPress={e=>{const p=state.data.properties.find(p=>p.id===e.features[0]?.properties?.id);if(p&&active)setSelected(p);}}><Mapbox.CircleLayer id="door-pins" style={{circleRadius:7,circleColor:['get','color'],circleStrokeWidth:2,circleStrokeColor:'#f9faf6'}}/><Mapbox.SymbolLayer id="door-labels" minZoomLevel={16} style={{textField:['get','label'],textSize:11,textOffset:[0,1.4],textColor:'#263d31',textHaloColor:'#f9faf6',textHaloWidth:2}}/><Mapbox.SymbolLayer id="door-symbols" style={{textField:['get','symbol'],textSize:12,textColor:'#f9faf6',textAllowOverlap:true}}/></Mapbox.ShapeSource></Mapbox.MapView>:<View style={s.mapEmpty}><Text style={s.h2}>Map setup required</Text><Text style={s.note}>Add the company’s Mapbox token to show streets and house pins.</Text></View>}<View style={s.mapActions}><Button title="Record a door at my location" disabled={busy||!active} onPress={()=>void run(()=>addDoor())}/><Button title={busy?'Downloading…':'Download assigned maps'} disabled={busy||offline} secondary onPress={()=>void run(download)}/></View></View>:null}
 {screen==='doors'?<ScrollView style={s.scroll}><Text style={s.h1}>Recorded doors</Text><Text style={s.note}>Visit history and follow-ups in your assigned areas.</Text>{[...state.data.properties].sort((a,b)=>Number(b.do_not_knock)-Number(a.do_not_knock)).map(p=>{const visits=state.data.visits.filter(v=>v.property_id===p.id).sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at)),v=visits[0];return <View key={p.id} style={s.doorRow}><Text style={s.rowTitle}>{p.address}</Text><Text style={{color:p.do_not_knock?outcomeColors.do_not_knock:v?outcomeColors[v.outcome]:'#64748b',fontSize:13,marginTop:5}}>{p.do_not_knock?'Do not knock':v?outcomeLabels[v.outcome]:'No visits'}</Text>{visits.slice(0,3).map(v=><Text key={v.id} style={s.note}>{dayKey(v.occurred_at)} · {outcomeLabels[v.outcome]}{v.notes?` · ${v.notes}`:''}{v.follow_up_at?` · Follow-up ${dayKey(v.follow_up_at)}`:''}</Text>)}<View style={s.shiftButtons}><Button title="Record visit" disabled={!active} onPress={()=>setSelected(p)}/><Button title="Directions" secondary onPress={()=>void Linking.openURL(Platform.OS==='ios'?`http://maps.apple.com/?daddr=${p.latitude},${p.longitude}`:`google.navigation:q=${p.latitude},${p.longitude}`)}/></View></View>;})}{!state.data.properties.length?<Text style={s.body}>Your first recorded house will appear here.</Text>:null}</ScrollView>:null}
 {screen==='time'?<TimeScreen state={state} busy={busy} onCorrection={(id,minutes,reason)=>void run(async()=>{await submit(command('correction',{shift_id:id,requested_minutes:minutes,reason}));setMessage('Correction request saved for your owner.');try{await sync();}catch{};})}/>:null}
 {screen==='sync'?<ScrollView style={s.scroll}><Text style={s.h1}>Saved on your phone</Text><Text style={s.body}>{entries.length} pending records. Your work stays here until the server confirms it.</Text><Text style={s.note}>Last sync: {state.last_sync?new Date(state.last_sync).toLocaleString():'Not yet synced'}</Text><Button title={busy?'Syncing…':'Sync now'} disabled={busy} onPress={()=>void run(connect)}/><Text style={s.note}>{state.downloaded_territory_ids.length} territories downloaded for offline maps.</Text>{entries.filter(e=>e.error).map(entry=><View key={entry.command.id} style={s.doorRow}><Text style={s.rowTitle}>{entry.command.kind} needs attention</Text><Text style={s.warningText}>{entry.error}</Text><Button title="Retry this record" secondary onPress={()=>void run(async()=>{await outbox.retry(entry.command.id);await connect();})}/></View>)}<Button title="Sign out" secondary disabled={busy} onPress={()=>void run(async()=>{if(active||status==='break')throw Error('Clock out before signing out.');await sync();await stopTracking();await clearLocal();})}/></ScrollView>:null}
 <View style={s.tabs}>{(['map','doors','time','sync'] as const).map(tab=><Pressable accessibilityRole="tab" accessibilityState={{selected:screen===tab}} key={tab} onPress={()=>setScreen(tab)} style={s.tab}><Text style={[s.tabText,screen===tab?{color:'#b83e29',fontWeight:'700'}:null]}>{tab==='map'?'Territory':tab==='doors'?'Doors':tab==='time'?'My hours':'Sync'}</Text></Pressable>)}</View></SafeAreaView>;
}
function Login({busy,message,onLogin}:{busy:boolean;message:string;onLogin:(email:string,password:string)=>void}){const [email,setEmail]=useState(''),[password,setPassword]=useState('');return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.login}><Text style={s.wordmark}>WE ROOF</Text><Text style={s.h1}>Your territory.<br/>Your next opportunity.</Text><Text style={s.body}>Sign in with your company’s invited account.</Text><Text style={s.label}>Email</Text><TextInput style={s.input} accessibilityLabel="Email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoComplete="email"/><Text style={s.label}>Password</Text><TextInput style={s.input} accessibilityLabel="Password" value={password} onChangeText={setPassword} secureTextEntry autoComplete="password"/>{message?<Text style={s.warningText}>{message}</Text>:null}<Button title={busy?'Signing in…':'Sign in'} disabled={busy||!email||!password} onPress={()=>onLogin(email,password)}/></ScrollView></SafeAreaView>;}
function PasswordSetup({onDone}:{onDone:()=>void}){const [password,setPassword]=useState(''),[error,setError]=useState('');return <SafeAreaView style={s.root}><View style={s.login}><Text style={s.h1}>Set your password</Text><TextInput accessibilityLabel="New password" style={s.input} value={password} onChangeText={setPassword} secureTextEntry/><Text style={s.warningText}>{error}</Text><Button title="Save password" disabled={password.length<8} onPress={()=>void supabase!.auth.updateUser({password}).then(({error})=>error?setError(error.message):onDone())}/></View></SafeAreaView>;}
function DoorForm({state,property,busy,cancel,save}:{state:LocalState;property:Property;busy:boolean;cancel:()=>void;save:(payload:Record<string,unknown>)=>void}){const [address,setAddress]=useState(property.address),[outcome,setOutcome]=useState<Outcome>('no_answer'),[notes,setNotes]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[concerns,setConcerns]=useState(''),[preferred,setPreferred]=useState(''),[followUp,setFollowUp]=useState(''),[ack,setAck]=useState(false),[gps,setGps]=useState<Position|null>(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true;void Location.getForegroundPermissionsAsync().then(async(permission)=>{if(!permission.granted)return;const p=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});if(alive)setGps({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy??999,captured_at:new Date(p.timestamp).toISOString()});}).catch(()=>{});return()=>{alive=false;};},[]);
 const needsLead=outcome==='interested'||outcome==='inspection_requested';const input=(label:string,value:string,set:(value:string)=>void,keyboard:'default'|'phone-pad'|'email-address'='default')=><View><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} style={s.input} value={value} onChangeText={set} keyboardType={keyboard} autoCapitalize={keyboard==='email-address'?'none':'sentences'}/></View>;
 function finish(){if(!address.trim()){setError('Enter the property address.');return;}if(needsLead){const err=validateLead({name,phone,email});if(err){setError(err);return;}}if(property.do_not_knock&&!ack){setError('Acknowledge the do-not-knock warning before recording.');return;}if(outcome==='follow_up'&&(!/^\d{4}-\d{2}-\d{2}$/.test(followUp)||!Number.isFinite(Date.parse(followUp)))){setError('Enter a follow-up date as YYYY-MM-DD.');return;}
 save({property:{...property,address:address.trim()},outcome,notes,gps,acknowledge_dnk:ack,follow_up_at:outcome==='follow_up'?new Date(`${followUp}T12:00:00-04:00`).toISOString():null,lead:needsLead?{id:Crypto.randomUUID(),name:name.trim(),phone:phone.trim(),email:email.trim(),concerns,preferred_window:preferred}:null});}
 return <SafeAreaView style={s.root}><View style={s.header}><Text style={s.h2}>Record a door</Text><Button title="Cancel" secondary onPress={cancel}/></View><ScrollView style={s.scroll} keyboardShouldPersistTaps="handled">{property.do_not_knock?<View style={s.warning}><Text style={s.warningText}>DO NOT KNOCK · This house is marked company-wide. Only your owner can clear it.</Text><Button title={ack?'Warning acknowledged':'Acknowledge warning'} secondary onPress={()=>setAck(true)}/></View>:null}{input('Property address',address,setAddress)}<Text style={s.note}>{gps?`GPS accuracy: ${Math.round(gps.accuracy)} metres`:'GPS unavailable; this record will be flagged for owner review.'}</Text><Text style={s.label}>Door outcome</Text><View style={s.outcomes}>{outcomes.map(o=><Pressable accessibilityRole="radio" accessibilityState={{selected:outcome===o}} key={o} onPress={()=>setOutcome(o)} style={[s.outcome,outcome===o?{borderColor:outcomeColors[o],backgroundColor:'#eff4ed'}:null]}><View style={[s.outcomeDot,{backgroundColor:outcomeColors[o]}]}/><Text style={s.outcomeText}>{outcomeLabels[o]}</Text></Pressable>)}</View>{outcome==='follow_up'?input('Follow-up date (YYYY-MM-DD)',followUp,setFollowUp):null}{needsLead?<><Text style={s.h2}>Homeowner details</Text>{input('Homeowner name',name,setName)}{input('Phone',phone,setPhone,'phone-pad')}{input('Email',email,setEmail,'email-address')}{input('Roofing concerns',concerns,setConcerns)}{outcome==='inspection_requested'?<>{input('Preferred inspection window',preferred,setPreferred)}<Text style={s.note}>Your office will confirm the appointment.</Text></>:null}</>:null}<Text style={s.label}>Field notes</Text><TextInput accessibilityLabel="Field notes" style={[s.input,{minHeight:90,textAlignVertical:'top'}]} multiline value={notes} onChangeText={setNotes}/>{error?<Text style={s.warningText}>{error}</Text>:null}<Button title={busy?'Saving…':'Save door record'} disabled={busy} onPress={finish}/><View style={{height:35}}/></ScrollView></SafeAreaView>;
}
function TimeScreen({state,busy,onCorrection}:{state:LocalState;busy:boolean;onCorrection:(shiftId:string,minutes:number,reason:string)=>void}){const [selected,setSelected]=useState<string|null>(null),[minutes,setMinutes]=useState(''),[reason,setReason]=useState('');const ids=[...new Set(state.data.events.filter(e=>e.user_id===state.user?.user_id).sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at)).map(e=>e.shift_id))];return <ScrollView style={s.scroll}><Text style={s.h1}>My field hours</Text><Text style={s.note}>Breaks pause field time. Approved corrections preserve your original shift.</Text>{ids.map(id=>{const events=state.data.events.filter(e=>e.shift_id===id),start=events.find(e=>e.action==='clock_in');return <View style={s.doorRow} key={id}><Text style={s.rowTitle}>{start?dayKey(start.occurred_at):'Shift'} · {fmt(fieldMinutes(events))}</Text>{events.map(e=><Text key={e.id} style={s.note}>{e.action.replaceAll('_',' ')} · {new Date(e.occurred_at).toLocaleTimeString()}</Text>)}{state.data.corrections.filter(c=>c.shift_id===id).map(c=><Text key={c.id} style={s.note}>{c.requested_minutes>0?'+':''}{c.requested_minutes} min correction · {c.status}</Text>)}<Button title="Request time correction" secondary onPress={()=>{setSelected(id);setReason('');setMinutes('');}}/></View>;})}{selected?<View style={s.doorRow}><Text style={s.h2}>Request a correction</Text><Text style={s.label}>Minutes to add or subtract</Text><TextInput accessibilityLabel="Correction minutes" style={s.input} value={minutes} onChangeText={setMinutes} keyboardType="numbers-and-punctuation" placeholder="15 or -15"/><Text style={s.label}>Reason</Text><TextInput accessibilityLabel="Correction reason" style={s.input} value={reason} onChangeText={setReason}/><Button title="Send to owner" disabled={busy||!reason.trim()||!minutes||!Number.isInteger(Number(minutes))||Math.abs(Number(minutes))>1440} onPress={()=>{onCorrection(selected,Number(minutes),reason);setSelected(null);}}/></View>:null}</ScrollView>;}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#f9faf6'},header:{paddingHorizontal:20,paddingVertical:13,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#dde4db'},wordmark:{fontSize:28,fontWeight:'700',letterSpacing:-1,color:'#b83e29'},small:{fontSize:12,color:'#65766d',marginTop:3},h1:{fontSize:29,fontWeight:'600',color:'#282b2a',lineHeight:35,marginVertical:20,letterSpacing:-.8},h2:{fontSize:17,fontWeight:'600',color:'#282b2a',marginVertical:8},body:{fontSize:15,color:'#50635a',lineHeight:23,marginBottom:20},note:{fontSize:12,color:'#65766d',lineHeight:19,marginVertical:5},label:{fontSize:13,fontWeight:'600',color:'#343634',marginTop:19,marginBottom:8},input:{borderWidth:1,borderColor:'#cdd8cd',backgroundColor:'#fdfefb',borderRadius:7,minHeight:48,padding:12,color:'#282b2a',fontSize:15},login:{padding:28,flexGrow:1,justifyContent:'center'},button:{backgroundColor:'#b83e29',borderRadius:7,minHeight:45,justifyContent:'center',alignItems:'center',paddingHorizontal:14,paddingVertical:12,marginVertical:5},buttonText:{color:'#f9faf6',fontSize:13,fontWeight:'600'},secondary:{backgroundColor:'#f6eeea',borderWidth:1,borderColor:'#d5dfd4'},statusPill:{borderRadius:20,backgroundColor:'#f6eeea',padding:10},statusText:{fontSize:12,color:'#b83e29',fontWeight:'600'},shiftBar:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',padding:20,borderBottomWidth:1,borderBottomColor:'#dde4db'},sectionLabel:{fontSize:10,letterSpacing:1.3,fontWeight:'600',color:'#65766d'},shiftTime:{fontSize:28,fontWeight:'600',color:'#282b2a',marginTop:6},shiftButtons:{flexDirection:'row',gap:7,flexWrap:'wrap'},warning:{backgroundColor:'#fff1df',padding:14,margin:10,borderRadius:7},warningText:{color:'#85480e',fontSize:12,lineHeight:20},message:{backgroundColor:'#f6eeea',padding:10,marginHorizontal:12,borderRadius:7},scroll:{padding:20,flex:1},mapContent:{flex:1},mapHeading:{paddingHorizontal:20,paddingVertical:8},mapActions:{paddingHorizontal:15,paddingVertical:7},mapEmpty:{flex:1,alignItems:'center',justifyContent:'center',padding:25},tabs:{flexDirection:'row',borderTopWidth:1,borderTopColor:'#dde4db',backgroundColor:'#f9faf6'},tab:{flex:1,paddingVertical:18,alignItems:'center',minHeight:50},tabText:{fontSize:12,color:'#65766d'},doorRow:{paddingVertical:18,borderBottomWidth:1,borderBottomColor:'#dde4db'},rowTitle:{fontSize:15,fontWeight:'600',color:'#282b2a',lineHeight:22},outcomes:{flexDirection:'row',flexWrap:'wrap',gap:8,marginVertical:8},outcome:{flexDirection:'row',gap:7,alignItems:'center',padding:12,borderWidth:1,borderColor:'#d5dfd4',borderRadius:7,minHeight:46},outcomeDot:{width:7,height:7,borderRadius:4},outcomeText:{fontSize:12,color:'#343634'}});
