export class CRMError extends Error {constructor(message:string,public uncertain=false){super(message);}}
type RecordData=Record<string,unknown>;
export class JobNimbus {
 constructor(private key:string,private request:typeof fetch=fetch){}
 async call(path:string,body?:RecordData):Promise<RecordData>{let response:Response;try{response=await this.request(`https://app.jobnimbus.com/api1/${path}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${this.key}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});}catch{throw new CRMError('JobNimbus request timed out or connection dropped',Boolean(body));}
  if(!response.ok)throw new CRMError(`JobNimbus returned HTTP ${response.status}`,Boolean(body)&&response.status>=500);
  try{return await response.json();}catch{throw new CRMError('JobNimbus returned an unreadable response',Boolean(body));}
 }
 async findContact(externalId:string){const query=new URLSearchParams({size:'2',filter:JSON.stringify({must:[{term:{external_id:externalId}}]})});const data=await this.call(`contacts?${query}`);const rows=(Array.isArray(data)?data:data.results??data.data) as RecordData[]|undefined;if(!Array.isArray(rows))throw new CRMError('Unexpected contact search response');if(rows.length>1)throw new CRMError('Multiple JobNimbus contacts match this property',true);return rows[0]?.jnid?String(rows[0].jnid):null;}
 async createContact(payload:RecordData){const result=await this.call('contacts',payload);if(!result.jnid)throw new CRMError('Contact created without a readable record ID',true);return String(result.jnid);}
 async createTask(payload:RecordData){const result=await this.call('tasks',payload);if(!result.jnid)throw new CRMError('Task created without a readable record ID',true);return String(result.jnid);}
}
export function contactPayload(lead:RecordData,property:RecordData,repName:string,workflow:string,status:string){const names=String(lead.name).trim().split(/\s+/);return {first_name:names[0],last_name:names.slice(1).join(' '),record_type_name:workflow,status_name:status,external_id:`fieldwork-property:${property.id}`,address_line1:String(property.address).split(',')[0],description:`Fieldwork lead ${lead.id}\nProperty: ${property.address}\nCanvasser: ${repName}\nRoofing concerns: ${lead.concerns}\nNotes: ${lead.notes}\nPreferred inspection: ${lead.preferred_window||'Office to arrange'}\nOffice must confirm inspection.`,mobile_phone:lead.phone,email:lead.email,geo:{lat:property.latitude,lon:property.longitude}};}
export function taskPayload(lead:RecordData,contactId:string,repName:string,type:string,assignee:string,now=Date.now()){return {title:`Fieldwork inspection follow-up · ${lead.name} · ${lead.id}`,description:`Confirm an inspection with the homeowner.\nRequested window: ${lead.preferred_window||'Office to arrange'}\nCanvasser: ${repName}\nRoofing concerns: ${lead.concerns}\n${lead.notes||''}`,record_type_name:type,related:[{id:contactId}],owners:[{id:assignee}],date_start:Math.floor(now/1000),date_end:0};}
