import {type Dataset,type Outcome,type ShiftEvent} from '@canvass/core';
export const DEMO_COMPANY='00000000-0000-4000-8000-000000000001';
export const OWNER='00000000-0000-4000-8000-000000000002';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
export function makeDemo():Dataset {
 const now=Date.now(), at=(minutes:number)=>new Date(now-minutes*60000).toISOString();
 const reps=[{user_id:id(3),company_id:DEMO_COMPANY,name:'Alex Morgan',email:'alex@example.com',role:'canvasser' as const,active:true},{user_id:id(4),company_id:DEMO_COMPANY,name:'Jordan Davis',email:'jordan@example.com',role:'canvasser' as const,active:true},{user_id:id(5),company_id:DEMO_COMPANY,name:'Casey Wilson',email:'casey@example.com',role:'canvasser' as const,active:true},{user_id:id(6),company_id:DEMO_COMPANY,name:'Taylor Reed',email:'taylor@example.com',role:'canvasser' as const,active:true}];
 const territories=[{id:id(10),company_id:DEMO_COMPANY,name:'Oakwood Heights',color:'#147b70',assigned_user_ids:[id(3),id(4)],archived:false,boundary:{type:'Polygon' as const,coordinates:[[[-78.179,39.178],[-78.159,39.178],[-78.159,39.164],[-78.179,39.164],[-78.179,39.178]]]}},{id:id(11),company_id:DEMO_COMPANY,name:'Cedar Ridge',color:'#546eb6',assigned_user_ids:[id(5),id(6)],archived:false,boundary:{type:'Polygon' as const,coordinates:[[[-78.156,39.183],[-78.139,39.183],[-78.139,39.169],[-78.156,39.169],[-78.156,39.183]]]}}];
 const status:Outcome[]=['no_answer','not_interested','follow_up','interested','inspection_requested','existing_customer','do_not_knock'];
 const properties=Array.from({length:47},(_,i)=>({id:id(100+i),company_id:DEMO_COMPANY,territory_id:i<29?id(10):id(11),created_by:reps[i%4].user_id,address:`${204+i*2} ${i<29?['Oakwood Avenue','Willow Lane','Maple Street'][i%3]:['Cedar Drive','Ridge Road'][i%2]}, Winchester, VA`,latitude:39.166+(i%7)*.0019,longitude:i<29?-78.176+Math.floor(i/7)*.0038:-78.153+Math.floor((i-29)/7)*.0038,do_not_knock:status[i%7]==='do_not_knock',version:1}));
 const visits=properties.map((p,i)=>({id:id(200+i),company_id:DEMO_COMPANY,property_id:p.id,user_id:reps[i%4].user_id,shift_id:id(20+i%4),outcome:status[i%7],notes:i%7===4?'Homeowner noticed missing shingles after the last storm. Office to confirm inspection.':i%7===2?'Homeowner asked us to come back after 5 pm.':'',occurred_at:at(5+i*2.4),gps:{latitude:p.latitude,longitude:p.longitude,accuracy:8,captured_at:at(5+i*2.4)},follow_up_at:i%7===2?new Date(now+86400000).toISOString():null}));
 const events:ShiftEvent[]=reps.flatMap((r,i)=>[{id:id(300+i*3),shift_id:id(20+i),user_id:r.user_id,action:'clock_in' as const,occurred_at:at(155-i*7)},...(i===1?[{id:id(301+i*3),shift_id:id(20+i),user_id:r.user_id,action:'break_start' as const,occurred_at:at(2)}]:i===3?[{id:id(301+i*3),shift_id:id(20+i),user_id:r.user_id,action:'clock_out' as const,occurred_at:at(3)}]:[])]);
 const leads=visits.filter(v=>['interested','inspection_requested'].includes(v.outcome)).map((v,i)=>({id:id(400+i),company_id:DEMO_COMPANY,visit_id:v.id,property_id:v.property_id,user_id:v.user_id,name:['Robert Mitchell','Sarah Thompson','James Parker','Emily Brooks','David Foster','Susan Hayes','Michael Ross','Linda Carter','Thomas Ellis','Anna Wright','Paul Martin','Nancy Hill','Daniel Green','Mary Lewis'][i],phone:`540-555-${String(100+i).padStart(4,'0')}`,email:'',concerns:i%2?'Missing shingles / storm damage':'Roof age / replacement',notes:v.notes,preferred_window:i%2?'Tomorrow afternoon':'',sync_status:i===2?'failed' as const:i===3?'pending' as const:'synced' as const,remote_contact_id:i===2||i===3?null:`demo-${i}`,created_at:v.occurred_at}));
 const locations=reps.slice(0,3).flatMap((r,i)=>Array.from({length:12},(_,j)=>({id:id(500+i*12+j),company_id:DEMO_COMPANY,user_id:r.user_id,shift_id:id(20+i),latitude:39.168+j*.0006,longitude:(i===2?-78.152:-78.174+i*.005)+Math.sin(j*.5)*.0014,accuracy:9,captured_at:at(i===1?12+j*.5:(11-j)*.5)})));
 return {members:[{user_id:OWNER,company_id:DEMO_COMPANY,name:'Company Owner',email:'owner@example.com',role:'owner',active:true},...reps],territories,properties,visits,leads,events,locations,flags:[{id:id(700),company_id:DEMO_COMPANY,visit_id:visits[8].id,user_id:id(3),reason:'Away from property',detail:'GPS reading was 112 metres from the house pin.',resolved_at:null,created_at:at(24)},{id:id(701),company_id:DEMO_COMPANY,visit_id:visits[15].id,user_id:id(5),reason:'GPS unverified',detail:'Location accuracy was 86 metres. Visit preserved for review.',resolved_at:null,created_at:at(40)}],corrections:[{id:id(800),company_id:DEMO_COMPANY,shift_id:id(23),user_id:id(6),requested_minutes:15,reason:'Forgot to clock in when we arrived at the territory.',status:'pending',created_at:at(30)}]};
}
