import {lazy,Suspense,useState} from 'react';
import {Plus,Minus,LocateFixed,Layers,Navigation,MapPin} from 'lucide-react';
import {latestVisit,outcomeColors,outcomeLabels,routeSegments,type Dataset,type Property} from '@canvass/core';
const LiveMap=lazy(()=>import('./LiveMap'));
export type MapProps={data:Dataset;focusedRep:string|null;onProperty:(property:Property)=>void;drawPoints:number[][]|null;onDrawPoint:(point:number[])=>void;showRoutes:boolean;selectedTerritory:string;mode:'demo'|'live'};
export const extent={west:-78.182,east:-78.135,south:39.160,north:39.186};
export function xy(lon:number,lat:number){return [(lon-extent.west)/(extent.east-extent.west)*1000,(extent.north-lat)/(extent.north-extent.south)*620];}
export function coordinates(x:number,y:number){return [extent.west+x/1000*(extent.east-extent.west),extent.north-y/620*(extent.north-extent.south)];}
export default function TerritoryMap(props:MapProps){const [zoom,setZoom]=useState(1);const token=import.meta.env.VITE_MAPBOX_TOKEN;
 return <div className="map-wrap">{token?<Suspense fallback={<div className="map-loading">Loading territory map…</div>}><LiveMap {...props} token={token}/></Suspense>:props.mode==='demo'?<DemoMap {...props} zoom={zoom}/>:<div className="map-loading"><MapPin size={32}/><h3>Connect your map</h3><p>Add your Mapbox token to display real territories.</p></div>}
 {props.mode==='demo'&&!token?<><div className="map-controls"><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(2,z+.2))}><Plus size={18}/></button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(1,z-.2))}><Minus size={18}/></button><button aria-label="Reset map view" onClick={()=>setZoom(1)}><LocateFixed size={18}/></button></div><div className="map-attribution">Illustrative demo map · Sample properties</div></>:null}
 <div className="map-tag"><Layers size={15}/>{props.selectedTerritory==='all'?'Assigned territories':props.data.territories.find(t=>t.id===props.selectedTerritory)?.name}</div>
 {props.drawPoints!==null?<div className="draw-instruction"><Navigation size={16}/>Click the map to place boundary corners · {props.drawPoints.length} points</div>:null}
 </div>;
}
function DemoMap({data,focusedRep,onProperty,drawPoints,onDrawPoint,showRoutes,selectedTerritory,zoom}:MapProps&{zoom:number}) {
 const visible=data.territories.filter(t=>!t.archived&&(selectedTerritory==='all'||t.id===selectedTerritory));
 const roadsX=[100,230,360,490,620,750,880],roadsY=[85,195,305,415,525];
 return <svg className="demo-map" viewBox={`${500-500/zoom} ${310-310/zoom} ${1000/zoom} ${620/zoom}`} role="img" aria-label="Illustrative territory map with recorded doors and sample canvasser positions" onClick={e=>{if(drawPoints===null)return;const svg=e.currentTarget;const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const transformed=p.matrixTransform(svg.getScreenCTM()!.inverse());onDrawPoint(coordinates(transformed.x,transformed.y));}}>
 <defs><pattern id="lots" width="130" height="110" patternUnits="userSpaceOnUse"><rect width="130" height="110" fill="#e9e9df"/><path d="M0 55H130M65 0V110" stroke="#d6d8cc" strokeWidth="1"/><rect x="12" y="13" width="29" height="20" rx="2" fill="#d3d1c5" stroke="#c3c2b5"/><rect x="83" y="16" width="28" height="19" rx="2" fill="#d3d1c5" stroke="#c3c2b5"/><rect x="14" y="74" width="30" height="22" rx="2" fill="#d3d1c5" stroke="#c3c2b5"/><rect x="85" y="72" width="25" height="20" rx="2" fill="#d3d1c5" stroke="#c3c2b5"/></pattern></defs>
 <rect width="1000" height="620" fill="url(#lots)"/>
 <path d="M740 -30Q700 160 805 220T860 440T920 650" stroke="#bcd8d4" strokeWidth="30" fill="none"/><path d="M740 -30Q700 160 805 220T860 440T920 650" stroke="#cce4e1" strokeWidth="18" fill="none"/>
 <path d="M25 25L210 20L190 150L45 150Z" fill="#d4dfc4"/><path d="M625 460L720 440L795 565L645 590Z" fill="#d4dfc4"/>
 {roadsX.map(x=><g key={x}><path d={`M${x} 0V620`} stroke="#d3d2c7" strokeWidth="18"/><path d={`M${x} 0V620`} stroke="#f8f7f1" strokeWidth="14"/></g>)}
 {roadsY.map(y=><g key={y}><path d={`M0 ${y}H1000`} stroke="#d3d2c7" strokeWidth="18"/><path d={`M0 ${y}H1000`} stroke="#f8f7f1" strokeWidth="14"/></g>)}
 <path d="M-20 590L1020 20" stroke="#c5c4b5" strokeWidth="28"/><path d="M-20 590L1020 20" stroke="#f9f6e9" strokeWidth="24"/><path d="M-20 590L1020 20" stroke="#dcd1a7" strokeWidth="1" strokeDasharray="10 8"/>
 <g fontFamily="system-ui" fontSize="10" fill="#898d80" letterSpacing="1"><text x="220" y="77">WILLOW LANE</text><text x="380" y="297">OAKWOOD AVENUE</text><text x="650" y="187">CEDAR DRIVE</text><text x="250" y="517">MAPLE STREET</text><text x="140" y="135">OAKWOOD PARK</text><text x="652" y="555">RIDGE GREEN</text></g>
 {visible.map(t=><g key={t.id}><polygon points={t.boundary.coordinates[0].map(([lon,lat])=>xy(lon,lat).join(',')).join(' ')} fill={t.color} fillOpacity=".075" stroke={t.color} strokeWidth="2" strokeDasharray="7 5"/><text x={xy(t.boundary.coordinates[0][0][0],t.boundary.coordinates[0][0][1])[0]+12} y={xy(t.boundary.coordinates[0][0][0],t.boundary.coordinates[0][0][1])[1]+26} fill={t.color} fontSize="13" fontWeight="650">{t.name}</text></g>)}
 {showRoutes?data.members.filter(m=>m.role==='canvasser'&&(!focusedRep||m.user_id===focusedRep)).flatMap(m=>routeSegments(data.locations.filter(l=>l.user_id===m.user_id),data.events).filter(s=>s.length>1).map((segment,i)=><polyline key={`${m.user_id}-${i}`} points={segment.map(p=>xy(p.longitude,p.latitude).join(',')).join(' ')} fill="none" stroke="#258671" strokeWidth="3" strokeOpacity=".6" strokeLinecap="round"/>)):null}
 {data.properties.filter(p=>selectedTerritory==='all'||p.territory_id===selectedTerritory).map(p=>{const [x,y]=xy(p.longitude,p.latitude),v=latestVisit(data.visits,p.id),color=p.do_not_knock?outcomeColors.do_not_knock:v?outcomeColors[v.outcome]:'#64748b';return <g key={p.id} className="door-pin" role="button" tabIndex={drawPoints===null?0:-1} aria-label={`${p.address}, ${p.do_not_knock?'Do not knock':v?outcomeLabels[v.outcome]:'No visits'}`} onClick={e=>{if(drawPoints!==null)return;e.stopPropagation();onProperty(p);}} onKeyDown={e=>{if(e.key==='Enter'&&drawPoints===null)onProperty(p);}}><title>{p.address}</title><circle cx={x} cy={y} r="8.5" fill={color} stroke="#fafbf7" strokeWidth="2.5"/>{p.do_not_knock?<path d={`M${x-3} ${y-3}l6 6m-6 0l6 -6`} stroke="#fafbf7" strokeWidth="1.5"/>:v?.outcome==='inspection_requested'?<path d={`M${x-3} ${y}l2 2 4 -4`} stroke="#fafbf7" strokeWidth="1.5" fill="none"/>:null}</g>;})}
 {data.members.filter(m=>m.role==='canvasser'&&m.active&&(!focusedRep||focusedRep===m.user_id)).map(m=>{const p=data.locations.filter(p=>p.user_id===m.user_id).sort((a,b)=>b.captured_at.localeCompare(a.captured_at))[0];if(!p)return null;const [x,y]=xy(p.longitude,p.latitude);return <g key={m.user_id}><circle cx={x} cy={y} r="23" fill="#147b70" opacity=".12"/><circle cx={x} cy={y} r="15" fill="#174c3c" stroke="#fafbf7" strokeWidth="3"/><text x={x} y={y+4} textAnchor="middle" fill="#fafbf7" fontSize="10" fontWeight="700">{m.name.split(' ').map(n=>n[0]).join('')}</text></g>;})}
 {drawPoints!==null?<g><polyline points={drawPoints.map(([lon,lat])=>xy(lon,lat).join(',')).join(' ')} fill="#147b70" fillOpacity=".15" stroke="#174c3c" strokeWidth="3"/>{drawPoints.map(([lon,lat],i)=>{const [x,y]=xy(lon,lat);return <circle key={i} cx={x} cy={y} r="6" fill="#174c3c" stroke="#fafbf7" strokeWidth="2"/>;})}</g>:null}
 </svg>;
}
